### ISSUE TITLE
crate2nix doesn't respect the toolchain file

### ISSUE THREAD

**Issue by JCapucho** [yusdacra/nix-cargo-integration#6]
When using the crate2nix build platform in this test repo https://github.com/JCapucho/cargo-nix-bug the build fails with the error

```
 error[E0554]: `#![feature]` may not be used on the stable release channel
   --> src/main.rs:1:1
    |
  1 | #![feature( try_trait)]
    | ^^^^^^^^^^^^^^^^^^^^^^^
  
  error: aborting due to previous error
  
  For more information about this error, try `rustc --explain E0554`.
cannot build derivation '/nix/store/whlyx870515cdarmc2ib0zyg0gxpg6mk-rust_nix-bug-0.1.0-linked.drv': 1 dependencies couldn't be built
```

This seems to be a problem with crate2nix itself but it would be nice to at least add a note in the readme.

**Comment by yusdacra** [comment]
It was nix-cargo-integration's fault, apparently it broke with 0dc180f974f764eed2321f44e8ea90319fb8b7f8. The CI didn't catch it because it is failing for something unrelated.

**Comment by JCapucho** [comment]
Thank you for your quick response and fix :)
